name: CI/CD

on:
  push:
    branches: [ main, staging, dev ]
    tags:
      - 'v*'
  pull_request:
    branches: [ dev, main, staging ]

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/todo-app:${{ github.sha }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests in Docker
        run: |
          docker pull ghcr.io/${{ github.repository }}/todo-app:${{ github.sha }}
          docker run --rm ghcr.io/${{ github.repository }}/todo-app:${{ github.sha }} pytest todo_project/tests/

  sast:
    needs: [build, test]
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Perform Bandit Analysis
      uses: PyCQA/bandit-action@v1
      with:
        targets: 'todo_project'

  dependency-check:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'Task-Manager-using-Flask'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Dependency-Check results
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check Report
          path: ${{github.workspace}}/reports

  open-pr-to-staging:
    needs: [build, test, sast, dependency-check]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && success()
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Pull Request
        id: create-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "dev"
          destination_branch: "staging"
          pr_title: "Merge dev into staging"
          pr_body: "Auto-generated PR to merge dev into staging after successfully passing all the tests."
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Review Environment
        if: steps.create-pr.outputs.pr_number
        env:
          PR_NUMBER: ${{ steps.create-pr.outputs.pr_number }}
        run: |
          echo "Creating review environment for PR $PR_NUMBER"
      - name: Comment PR with simulated environment URL
        if: steps.create-pr.outputs.pr_number
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.create-pr.outputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Review environment created'
            })

  create-review-env:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'staging' && github.head_ref != 'dev'
    steps:
      - uses: actions/checkout@v4
      - name: Create Review Environment
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "Creating review environment for PR $PR_NUMBER"
      - name: Comment PR with environment URL
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Review environment created'
            })

  dast:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v4
      - name: Run Docker container
        run: |
          docker pull ghcr.io/${{ github.repository }}/todo-app:${{ github.sha }}
          docker run -d -p 5000:5000 --name todo-container ghcr.io/${{ github.repository }}/todo-app:${{ github.sha }}
          sleep 10
      - name: Run ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://localhost:5000'
          allow_issue_writing: false
          
  deploy-staging:
    needs: dast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy staging
        run: |
          echo "Deploy app to staging"

  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy prod
        run: |
          echo "Deploy app to prod"

  post-deployment-monitoring:
    runs-on: ubuntu-latest
    needs: deploy-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Prometheus and Grafana
        run: |
          sudo apt-get update
          sudo apt-get install -y prometheus grafana

      - name: Configure Monitoring
        run: |
          echo "Prometheus"
          echo "Grafana"

      - name: Start Monitoring Services
        run: |
          sudo systemctl start prometheus
          sudo systemctl start grafana-server
